hard_tabs = true
imports_layout = "Vertical"
imports_granularity = "One"
space_before_colon = true
space_after_colon = true
edition = "2024"
brace_style = "AlwaysNextLine"
combine_control_expr = false
control_brace_style = "AlwaysNextLine"
fn_single_line = true
force_multiline_blocks = true
format_strings = true
hex_literal_case = "Upper"
match_block_trailing_comma = true
max_width = 80
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
blank_lines_upper_bound = 0
